# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{haskellPackages ? (import <nixpkgs>{}).haskellPackages}: with haskellPackages;

cabal.mkDerivation (self: {
  pname = "Ratscrew";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ mtl lens ];
  testDepends = [ tasty tastyHunit tastyQuickcheck ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
